/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Blogs: () => import('#controllers/blogs_controller'),
  Employees: () => import('#controllers/employees_controller'),
  Gallery: () => import('#controllers/gallery_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Projects: () => import('#controllers/projects_controller'),
  Users: () => import('#controllers/users_controller'),
}
