/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BlogSchema extends BaseModel {
  static $columns = ['authorId', 'category', 'content', 'coverImage', 'createdAt', 'deletedAt', 'deletedBy', 'id', 'slug', 'tags', 'title', 'updatedAt'] as const
  $columns = BlogSchema.$columns
  @column()
  declare authorId: number | null
  @column()
  declare category: string | null
  @column()
  declare content: string
  @column()
  declare coverImage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare slug: string | null
  @column()
  declare tags: any | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmployeeSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'deletedBy', 'email', 'id', 'name', 'phone', 'position', 'status', 'updatedAt'] as const
  $columns = EmployeeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: number | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column()
  declare phone: string | null
  @column()
  declare position: string | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GallerySchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'deletedBy', 'description', 'height', 'id', 'imageName', 'imagePath', 'title', 'updatedAt', 'updatedBy', 'uploadedBy', 'width'] as const
  $columns = GallerySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: number | null
  @column()
  declare description: string | null
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageName: string
  @column()
  declare imagePath: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: number | null
  @column()
  declare uploadedBy: number
  @column()
  declare width: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
